"""
mlservice/models/deberta_model.py
===================================
Fine-tuned DeBERTa-v3-base for multi-head regression.

Architecture:
  DeBERTa encoder  ──►  [CLS] pooled representation (768-dim)
                   ──►  6 independent regression heads (one per dimension)
                        → relevance, depth, clarity, confidence, structure, sentiment
                        Each head: Linear(768→256) → GELU → Dropout → Linear(256→1) → Sigmoid → *100

Training objective: MSE loss summed across all 6 heads.
Fine-tuned on synthetic dataset (dataset.json) generated by GPT-4.
"""

import os
import json
import logging
import numpy as np
from typing import Dict, Optional

import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModel

logger = logging.getLogger(__name__)

# ─── Constants ────────────────────────────────────────────────────────────────
BASE_MODEL_NAME   = "microsoft/deberta-v3-base"
SAVED_MODEL_DIR   = os.path.join(os.path.dirname(os.path.dirname(__file__)), "saved_models", "deberta")
MAX_SEQ_LEN       = 512
DIMENSIONS        = ["relevance", "depth", "clarity", "confidence", "structure", "sentiment"]
DEVICE            = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ─── Model Architecture ───────────────────────────────────────────────────────

class RegressionHead(nn.Module):
    """Single scoring head for one dimension."""
    def __init__(self, hidden_size: int = 768, dropout: float = 0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(hidden_size, 256),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(256, 1),
            nn.Sigmoid(),   # Output in [0, 1]; multiply by 100 at inference
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class DeBERTaMultiHeadScorer(nn.Module):
    """
    DeBERTa encoder + 6 regression heads.
    Input  : token ids, attention mask, token type ids
    Output : dict of dimension → score (0-100)
    """
    def __init__(self, base_model_name: str = BASE_MODEL_NAME, dropout: float = 0.1):
        super().__init__()
        self.encoder   = AutoModel.from_pretrained(base_model_name)
        hidden_size    = self.encoder.config.hidden_size  # 768 for base
        self.heads     = nn.ModuleDict({
            dim: RegressionHead(hidden_size, dropout) for dim in DIMENSIONS
        })

    def forward(
        self,
        input_ids:      torch.Tensor,
        attention_mask: torch.Tensor,
        token_type_ids: Optional[torch.Tensor] = None,
    ) -> Dict[str, torch.Tensor]:
        outputs = self.encoder(
            input_ids=input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
        )
        # Use [CLS] token representation
        pooled = outputs.last_hidden_state[:, 0, :]  # (batch, 768)
        return {dim: self.heads[dim](pooled).squeeze(-1) for dim in DIMENSIONS}


# ─── Wrapper for load + predict ───────────────────────────────────────────────

class InterviewScorer:
    """
    High-level wrapper used by FastAPI.
    Handles model loading (from fine-tuned weights or fresh pre-trained),
    tokenization, inference, and fallback.
    """

    def __init__(self):
        self.model:     Optional[DeBERTaMultiHeadScorer] = None
        self.tokenizer: Optional[AutoTokenizer]          = None
        self.is_loaded: bool = False
        self.model_name: str = "not_loaded"

    # ── Loading ───────────────────────────────────────────────────────────────

    def load(self):
        """
        Try to load fine-tuned weights from saved_models/deberta/.
        Falls back to pre-trained DeBERTa without custom heads (rule-based scores).
        Falls back further to rule-based-only if no internet/model available.
        """
        weights_path = os.path.join(SAVED_MODEL_DIR, "pytorch_model.bin")
        config_path  = os.path.join(SAVED_MODEL_DIR, "config.json")

        try:
            logger.info(f"Loading tokenizer from {BASE_MODEL_NAME}…")
            self.tokenizer = AutoTokenizer.from_pretrained(
                SAVED_MODEL_DIR if os.path.exists(config_path) else BASE_MODEL_NAME,
                use_fast=True,
            )

            self.model = DeBERTaMultiHeadScorer(
                base_model_name=SAVED_MODEL_DIR if os.path.exists(config_path) else BASE_MODEL_NAME
            )

            if os.path.exists(weights_path):
                logger.info("Loading fine-tuned weights…")
                state_dict = torch.load(weights_path, map_location=DEVICE)
                self.model.load_state_dict(state_dict, strict=False)
                self.model_name = "deberta-v3-base-finetuned-interview"
            else:
                logger.warning("No fine-tuned weights found — using pre-trained encoder only. Scores will be approximate.")
                self.model_name = "deberta-v3-base-pretrained"

            self.model = self.model.to(DEVICE).float()
            self.model.eval()
            self.is_loaded = True
            logger.info(f"✅ Model loaded on {DEVICE}: {self.model_name}")

        except Exception as e:
            logger.error(f"Could not load DeBERTa model: {e}. Falling back to heuristic scoring.")
            self.is_loaded = False
            self.model_name = "heuristic-fallback"

    # ── Inference ─────────────────────────────────────────────────────────────

    def predict(self, input_text: str) -> Dict[str, float]:
        """
        Returns dict: {relevance, depth, clarity, confidence, structure, sentiment}
        Values are 0-100 floats.
        """
        if not self.is_loaded or self.model is None:
            return self._heuristic_predict(input_text)

        try:
            encoding = self.tokenizer(
                input_text,
                max_length=MAX_SEQ_LEN,
                padding="max_length",
                truncation=True,
                return_tensors="pt",
            )
            input_ids      = encoding["input_ids"].to(DEVICE)
            attention_mask = encoding["attention_mask"].to(DEVICE)
            token_type_ids = encoding.get("token_type_ids")
            if token_type_ids is not None:
                token_type_ids = token_type_ids.to(DEVICE)

            input_ids = input_ids.long()
            attention_mask = attention_mask.long()

            with torch.no_grad():
                raw = self.model(input_ids, attention_mask, token_type_ids)

            return {dim: round(float(raw[dim].cpu().item()) * 100, 2) for dim in DIMENSIONS}

        except Exception as e:
            logger.error(f"Inference error: {e}. Using heuristic fallback.")
            return self._heuristic_predict(input_text)

    # ── Heuristic fallback ────────────────────────────────────────────────────

    def _heuristic_predict(self, text: str) -> Dict[str, float]:
        """
        Rule-based approximation used when DeBERTa is unavailable.
        Designed to be reasonable, not perfect.
        """
        import re

        words   = re.findall(r"\b\w+\b", text.lower())
        n_words = max(len(words), 1)
        n_sents = max(len(re.split(r"[.!?]+", text)), 1)

        STRONG = {"achieved","built","led","delivered","designed","solved","improved","managed","created","implemented","ensured","reduced","increased"}
        WEAK   = {"maybe","perhaps","kind of","sort of","um","uh","like","you know","i think","not sure","probably","i guess"}
        TECH   = {"algorithm","api","database","docker","kubernetes","react","python","node","sql","nosql","aws","microservice","system","architecture","scalable","cache","queue","rest","grpc"}

        strong_count = sum(1 for w in words if w in STRONG)
        weak_count   = sum(1 for w in words if w in WEAK)
        tech_count   = sum(1 for w in words if w in TECH)

        confidence  = min(100, max(20, 60 + strong_count * 4 - weak_count * 6))
        depth       = min(100, max(10, 40 + n_words * 0.3 + tech_count * 3))
        clarity     = min(100, max(20, 70 - abs((n_words / n_sents) - 18) * 1.5))
        relevance   = min(100, max(30, 55 + tech_count * 2 + strong_count * 2))
        structure   = min(100, max(20, 45 + n_sents * 2))
        sentiment   = min(100, max(30, 60 + strong_count * 3 - weak_count * 3))

        return {
            "relevance":  round(float(relevance),  1),
            "depth":      round(float(depth),      1),
            "clarity":    round(float(clarity),    1),
            "confidence": round(float(confidence), 1),
            "structure":  round(float(structure),  1),
            "sentiment":  round(float(sentiment),  1),
        }

    # ── Serialization ────────────────────────────────────────────────────────

    def save(self, output_dir: str = SAVED_MODEL_DIR):
        """Save fine-tuned weights + tokenizer after training."""
        os.makedirs(output_dir, exist_ok=True)
        if self.model:
            torch.save(self.model.state_dict(), os.path.join(output_dir, "pytorch_model.bin"))
            logger.info(f"Model weights saved to {output_dir}/pytorch_model.bin")
        if self.tokenizer:
            self.tokenizer.save_pretrained(output_dir)
            logger.info(f"Tokenizer saved to {output_dir}")
        # Save dimension list for reference
        meta = {"dimensions": DIMENSIONS, "base_model": BASE_MODEL_NAME, "max_seq_len": MAX_SEQ_LEN}
        with open(os.path.join(output_dir, "score_meta.json"), "w") as f:
            json.dump(meta, f, indent=2)